### PR TITLE
Added necessary UIB changes to handle the undo and redo actions and to record a history of changes

### LINKED ISSUE #3: Add ability to undo/redo actions
Make sure the page updates the `menuTree`, `menu`, and `outputJSON` client states correctly when [this is added](https://github.com/ServiceNowDevProgram/Menu-Generating-Operations-Program-Widget-Custom-Component/issues/8)

### PR DESCRIPTION
**Pull request by ayleeandersen**
Resolves #3.

Also note that there is a corresponding [PR](https://github.com/ServiceNowDevProgram/Menu-Generating-Operations-Program-Widget-Custom-Component/pull/18) open for the custom component. 

This PR has the UIB changes necessary to make the undo and redo functionality actually work on the page. It's pointing to my copied custom component, but I can swap it out for the original/main custom component once the sister PR is approved and merged if need be. Just let me know if I need to make that or other changes 😄 

Screen Shot 2023-10-17 at 2 41 23 PM
Screen Shot 2023-10-17 at 2 41 37 PM

### CODE REVIEW

**Review by SapphicFire — APPROVED** [review]
Awesome work, thanks for this Aylee.

**Comment by SapphicFire** [comment]
I wonder if there would be value in providing a link to your component version or the other repo or a readme/gist on your variant for users that try it. It's an edge case so maybe not worth the effort, just thinking out loud

**Comment by SapphicFire** [comment]
Thanks as ever

**Comment by ayleeandersen** [comment]
> I wonder if there would be value in providing a link to your component version or the other repo or a readme/gist on your variant for users that try it. It's an edge case so maybe not worth the effort, just thinking out loud

@SapphicFire Happy to do so if you feel it would be valuable. My biggest hesitation is just that my variant will now be pointing to a "broken" component since it was using my re-deployed version of the custom component, not the original one. They could still try it out if they replaced my "Menu Builder H23" with the original "Menu Builder" though.

**Pull request merged**
