### PR TITLE
fixed URL link type in application menu for Hacktoberfest23 > Configuration > UI Builder

### PR DESCRIPTION
**Pull request by deepak-64742**
I have updated the URL link type in application menu from _'/now/ui/builder/app/UX_APP_SYS_ID'_ to _'/now/build/ui/apps/UX_APP_CONFIG_SYS_ID'_ for **Hacktoberfest23 > Configuration > UI Builder**, because clicking on it leads to the **'Page not found'**.

I have captured the URL _'https://abc.service-now.com/now/build/ui/apps/e68f26c797d6a1107720f0571153afbe'_ from **Now Experience Framework > UI Builder** and also got reference from [here](https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB1168187).

### CODE REVIEW

**Comment by niamccash** [comment]
Thank you for your contribution. However, it seems that the file changes in this Pull Request are incorrect. 

I am not sure why you needed to update the URL link as the original works for me, and the new one your specified goes to: 

image

Which then just redirects to the original URL.

Please review the files you have changed/added and ensure that all modifications are correct, valid, and align with the project’s goals and guidelines. Closing this for now. Once you make additional changes, feel free to re-open this Pull Request or create a new one.

**Comment by deepak-64742** [comment]
the current URL leads to me here:
image

but the URL I have changed leads to me the right page:
image

I thought may be the problem is same for everyone. anyway, if it's working fine. its ok, 
**But @niamccash can you please provide me the URL for current & newer that I have changed. It will help me to debug. thank you in advance.**

**Comment by niamccash** [comment]
HI @deepak-64742 
Your comment/note says '_/now/ui/builder/app/UX_APP_SYS_ID_' but the URL in your PR difference actually shows the **_original_** URL of '_/now/builder/ui/experience/fa8fe6c797d6a1107720f0571153af16_' which seems to be the correct URL. At least that one is working for me.

image

**Comment by deepak-64742** [comment]
Hey @niamccash, thank you for your time and consideration & sorry for the inconvenience with my words.

The URL's actually I need from your **browser's address bar** after clicking **"Hacktoberfest23 > Configuration > UI Builder"** in both cases after and before my changes.

Before changes the URL was **"/now/builder/ui/experience/fa8fe6c797d6a1107720f0571153af16"** in format of **"/now/builder/ui/experience/UX_APP_SYS_ID"** and it leads to me "Page not found"
image

So I have changed the URL to **"/now/build/ui/apps/e68f26c797d6a1107720f0571153afbe"** in format of **"/now/build/ui/apps/UX_APP_CONFIG_SYS_ID"** and its leads to me the UI Builder page for Menu Builder
image

**Note: I'm using Tokyo release**, so please can you also share the release that you are using, because I have also used this code on multiple instances with same release. Maybe I'm missing something, that I wants to know.

**Comment by niamccash** [comment]
@deepak-64742 I think perhaps it may be because you're on Tokyo release? My PDI is on Vancouver release. I checked a Utah release and I see the format is also /now/builder/ui/experience/UX_APP_SYS_ID

**Comment by deepak-64742** [comment]
I got it, Thank you very much @niamccash for your time and kind consideration. 😀

**Pull request closed without merging**
